name: Build Component in Native Environment

on:
  push:
    branches: [ main, 'sprint/**', 'release/**', master, develop ]
  pull_request:
    branches: [ main, 'sprint/**', 'release/**', master, develop ]

jobs:
  build-sceneset-on-pr:
    name: Build sceneset component in github rdkcentral
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rdkcentral/docker-rdk-ci:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          bash -x build_dependencies.sh

      - name: Native build
        run: |
          bash -x cov_build.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
